refactor: replace ColumnOption::DialectSpecific with ColumnOption::Comment
CeresDB/ceresdb pull request #167
Opened 2022-08-04 07:41 UTC by baojinri

# Which issue does this PR close?

Closes #158 

# Rationale for this change
 simplify code when parse "comment"

# What changes are included in this PR?
replace ColumnOption::DialectSpecific with ColumnOption::Comment when parse "comment"

# Are there any user-facing changes?
None

# How does this change test

- tested by the compiler
- existing UT

2022-08-04 07:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CeresDB/ceresdb?pullRequest=167) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CeresDB/ceresdb?pullRequest=167) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CeresDB/ceresdb?pullRequest=167) it.</sub>

2022-08-05 08:54 UTC, ShiKaiWi commented
@baojinri Would you add a test in the `tests` for creating table with comment?

2022-08-07 08:51 UTC, chunshao90 approved these changes
LGTM

2022-08-11 02:10 UTC, ShiKaiWi requested changes
Add a test case for comment in the `tests`.

2022-08-24 14:32 UTC, waynexia commented on sql/src/parser.rs
> +        let sql = "CREATE TABLE mytbl(c1 timestamp, c2 double comment 'id', c3 string comment 'name',) ENGINE = XX";
This case is good, can you also add one in our integration test suit https://github.com/CeresDB/ceresdb/blob/main/tests/cases/local/05_ddl/create_tables.sql?

2022-08-26 02:46 UTC, waynexia approved these changes

2022-08-26 02:55 UTC, ShiKaiWi approved these changes
Well done!

2022-08-26 02:55 UTC, merged