refactor: bump datafusion, arrow and parquet
CeresDB/ceresdb pull request #26
Opened 2022-06-09 09:28 UTC by waynexia

Signed-off-by: Ruihang Xia <waynestxia@gmail.com>

# Which issue does this PR close?

Closes #25 

# Rationale for this change
 
 

See #25 

# What changes are included in this PR?

Bump versions.
Target:

- Arrow: 15.0.0
- Parquet: 15.0.0
- DataFusion: 9.0.0 (an unofficial patch branch https://github.com/waynexia/arrow-datafusion/tree/v9.x)

New todo from this PR:
- initialize in `async fn build_scan_table_exec_plan()` should be put off to stream's `poll_next()`
- implement `ContextProvider::get_variable_type()` for `ContextProviderAdapter`
- support `PruningStatistics`'s new method `fn null_counts()` for `RowGroupPruningStatistics`

Significant change:
- rewrite `RecordBytesReader`.
- fix: RecordSchema will ignore ArrowSchema's metadata in https://github.com/CeresDB/ceresdb/pull/26/commits/6b8993c778701f90a6dfc55619a8d45a948d739e

# Are there any user-facing changes?
no
# How does this change test
Unit test

2022-06-17 02:54 UTC, waynexia commented
Change to `refactor` since this touches a lot of logic.

2022-06-17 06:54 UTC, waynexia commented on components/parquet/src/serialized_reader.rs
> -pub struct SerializedPageReader<T: Read> {
This struct is replaced by upstream `SerializedPageReader`

2022-06-17 06:54 UTC, waynexia commented on query_engine/src/df_execution_extension/prom_align.rs
> +    fn output_ordering(&self) -> Option<&[PhysicalSortExpr]> {
@jiacai2050 does `PromAlignExec` guarantee output ordering?

2022-06-21 06:54 UTC, ShiKaiWi commented on analytic_engine/src/sst/parquet/reader.rs
> +    let bytes = get_result
Is the `todo` is solved here?

2022-06-21 06:54 UTC, ShiKaiWi commented on benchmarks/src/parquet_bench.rs
> +                "\nParquetBench total rows of sst: {}, total batch num: {},
Remove white space after the colon.

2022-06-21 06:54 UTC, ShiKaiWi commented on query_engine/src/context.rs
> +        let context = SessionContext::with_state(state);
It seems only `context` is needed so how about this style:
```
let df_session_ctx = {
   // building the session ctx
};
```

2022-06-21 06:54 UTC, ShiKaiWi commented on query_engine/src/context.rs
> +            df_exec_ctx: context,
Rename `df_exec_ctx`  to `df_session_ctx`?

2022-06-21 06:54 UTC, ShiKaiWi commented on sql/src/provider.rs
> +    // todo: maybe support this
Shall we give more details about this `todo`?

2022-06-21 06:54 UTC, ShiKaiWi commented on table_engine/src/predicate/mod.rs
> +    // todo: check if this is correct
It is right to return None and we can remove this todo.

2022-06-21 06:54 UTC, ShiKaiWi commented on analytic_engine/src/sst/parquet/builder.rs
> +                arrow_record_batch_vec = Vec::new();
Is it better to reserve capacity according to the previous length.

2022-06-21 06:54 UTC, ShiKaiWi commented on analytic_engine/src/sst/parquet/builder.rs
> +    fn into_bytes(self) -> Vec<u8> {
The `EncodingBuffer` can be simplified (at least no need to wrap vector wth `Arc<Mutex>`) after the `RecordBytesReader` is refactored.

2022-06-22 02:20 UTC, jiacai2050 requested changes

2022-06-22 02:20 UTC, jiacai2050 commented on query_engine/src/context.rs
> +    df_exec_config: SessionConfig,
df_session_config

2022-06-22 02:20 UTC, jiacai2050 commented on query_engine/src/context.rs
> +            Arc::new(SingleDistinctToGroupBy::new()),
Could you link the PR number fixing this bug?

2022-06-22 02:20 UTC, jiacai2050 commented on query_engine/src/df_planner_extension/mod.rs
> +        ctx_state: &SessionState,
session_state

2022-06-22 02:20 UTC, jiacai2050 commented on query_engine/src/df_planner_extension/prom_align.rs
> +        _ctx_state: &SessionState,
session_state

2022-06-22 02:20 UTC, jiacai2050 commented on query_engine/src/df_planner_extension/table_scan_by_primary_key.rs
> +                // todo: check whether we should push this await down to the result stream.
I couldn't understand this comment, could you explain this in more details?

2022-06-22 02:20 UTC, jiacai2050 commented on table_engine/src/predicate/mod.rs
> +        None
Maybe add a comment to support this later?

2022-06-22 02:20 UTC, jiacai2050 commented on table_engine/src/provider.rs
> +        ctx: &SessionState,
state

2022-06-22 02:20 UTC, jiacai2050 commented on table_engine/src/provider.rs
> +        ctx: &SessionState,
state

2022-06-22 09:08 UTC, ShiKaiWi commented on query_engine/src/context.rs
> +        let df_exec_config = { self.df_session_config };
```rust
let df_session_ctx = {
    let mut state = default_session_builder(self.df_session_config)
        .with_query_planner(Arc::new(QueryPlannerAdapter)            
        .with_optimizer_rules(Self::logical_optimize_rules());
    let physical_optimizer = Self::apply_adapters_for_physical_optimize_rules(&state.physical_optimizers);
    state.physical_optimizers = physical_optimizer;
    
    SessionContext::with_state(state)
}
```

2022-06-23 06:24 UTC, ShiKaiWi approved these changes
LGTM

2022-06-23 08:21 UTC, jiacai2050 approved these changes
LGTM

2022-06-23 08:31 UTC, merged