edit: NumKeyColumns  to PrimaryKeyIndexes
CeresDB/ceresdb pull request #526
Opened 2022-12-30 08:55 UTC by dust1

# Which issue does this PR close?

Closes #

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

# How does this change test

2023-01-03 09:10 UTC, jiacai2050 commented
@dust1 Please update PR's description to tell us how you test this, and if there are any user changes.

2023-01-03 09:17 UTC, jiacai2050 commented on common_types/src/schema.rs
> +            Self::PrimaryKeyIndexes => "schema:primary_key_indexes",
`schema::primary_key_indexes`

2023-01-03 09:19 UTC, jiacai2050 commented on common_types/src/schema.rs
> +                self.primary_key_indexes
Isn't this duplicated with ToString method?

2023-01-03 09:19 UTC, jiacai2050 commented on common_types/src/schema.rs
> +            .filter_map(|n| match n.parse::<usize>() {
It should return Error when parse failed.

2023-01-04 07:57 UTC, jiacai2050 commented
@dust1 I realize this is a breaking change, you need update target branch to https://github.com/CeresDB/ceresdb/tree/breaking-changes.

Main doesn't accept breaking change now.

2023-01-04 07:58 UTC, dust1 commented
ok

2023-01-04 08:04 UTC, dust1 commented
Oops. I can't find the Settings in this pr to modify the target branch, I may need to recreate a pr

2023-01-04 08:07 UTC, jiacai2050 requested changes

2023-01-04 08:07 UTC, jiacai2050 commented on common_types/src/schema.rs
> +struct Indexes {
```
struct Indexes(Vec<usize>);
```

2023-01-04 08:07 UTC, jiacai2050 commented on common_types/src/schema.rs
> +        format!("{:?}", self.indexes)
We shouldn't rely on `debug format` to format indexes, what if it changed between different Rust version?
```
self.indexes.join(',')
```

This is enough.

2023-01-04 08:21 UTC, dust1 commented on common_types/src/schema.rs
> +                format!("{:?}", self.primary_key_indexes),
`self.primary_key_indexes` is `Vec<usize>`, it not implement `ToString`, so I use `join` to generate the value in the `HashMap`

2023-01-04 08:48 UTC, jiacai2050 commented on common_types/src/schema.rs
> +                format!("{:?}", self.primary_key_indexes),
The problem is we need to make sure to_string/parse_string is on pair.

I think you can just wrap it like this
```
Indexes(self.primary_key_indexes).to_string()
```

2023-01-04 08:49 UTC, dust1 commented on common_types/src/schema.rs
> +                format!("{:?}", self.primary_key_indexes),
got it!

2023-01-04 09:16 UTC, jiacai2050 commented
I think this PR is ready for merge, I will push some minor changes.

Thanks @dust1

2023-01-04 10:11 UTC, jiacai2050 approved these changes
LGTM

2023-01-04 10:12 UTC, merged