Feat partition table in proxy
CeresDB/ceresdb pull request #802
Opened 2023-04-03 03:28 UTC by chunshao90

## Which issue does this PR close?

Closes #

## Rationale for this change
 

## What changes are included in this PR?

## Are there any user-facing changes?

## How does this change test

2023-04-10 02:30 UTC, ShiKaiWi commented on analytic_engine/src/manifest/details.rs
> +        fn meta_update_add_table_with_partition_info(&self, table_id: TableId) -> MetaUpdate {
After this PR, is this method necessary?

2023-04-10 02:30 UTC, ShiKaiWi commented on integration_tests/cases/env/cluster/05_ddl/partition_table.result
> +String("partition_table_t"),String("CREATE TABLE `partition_table_t` (`tsid` uint64 NOT NULL, `t` timestamp NOT NULL, `name` string TAG, `id` int TAG, `value` double NOT NULL, PRIMARY KEY(tsid,t), TI
Maybe we should add a todo or file a issue for fix this problem.

2023-04-10 02:30 UTC, ShiKaiWi commented on integration_tests/src/database.rs
> +        let table_name = parse_table_name(&statements);
```suggestion
        let table_name = frontend::parse_table_name(&statements);
```

2023-04-10 02:30 UTC, ShiKaiWi commented on partition_table_engine/src/lib.rs
> +        Ok(None)
Shall we support open table?

2023-04-10 03:44 UTC, ShiKaiWi commented on server/src/proxy/grpc/route.rs
> +                        // router
这个不需要的话 remove 掉？

2023-04-10 03:44 UTC, ShiKaiWi commented on sql/src/frontend.rs
> +        let test_cases=vec![
```suggestion
        let test_cases = vec![
```

2023-04-10 03:44 UTC, ShiKaiWi commented on table_engine/src/engine.rs
> +    #[snafu(display("Invalid arguments, table:{table}, err:{}", source))]
```suggestion
    #[snafu(display("Invalid arguments, table:{table}, err:{source}"))]
```

2023-04-10 10:04 UTC, jiacai2050 requested changes

2023-04-10 10:04 UTC, jiacai2050 commented on catalog/src/schema.rs
> +        let table_id = match (self.table_id, table_id) {
```
let table_id = self.table_id.unwrap_or(table_id.unwrap_or(MIN))
```

2023-04-10 13:46 UTC, ShiKaiWi commented on catalog/src/schema.rs
> +        table_id: Option<TableId>,
Add FIXME for this line.

2023-04-10 13:46 UTC, ShiKaiWi commented on catalog_impls/src/volatile.rs
> +                                 request.catalog_name,request.schema_name,request.table_name),
```suggestion
                                 request.catalog_name, request.schema_name, request.table_name),
```

2023-04-10 13:46 UTC, ShiKaiWi commented on router/src/cluster_based.rs
> +    async fn fetch_partition_table_info(
It seems the cache is not used here.

2023-04-10 13:46 UTC, ShiKaiWi commented on server/src/grpc/meta_event_service/mod.rs
> +    };
Maybe we can do this on L338

2023-04-10 13:46 UTC, ShiKaiWi commented on server/src/proxy/grpc/sql_query.rs
> +    async fn open_partition_table_if_not_exist(
```suggestion
    async fn maybe_open_partition_table_if_not_exist(
```

2023-04-11 07:09 UTC, jiacai2050 approved these changes
LGTM

2023-04-11 07:10 UTC, merged